### ISSUE TITLE
Requirements.txt gives following error

### ISSUE THREAD

**Issue by nehashinde-canopy** [katanaml/sparrow-donut#1]
ERROR: Cannot install -r requirements.txt (line 25) and haystack-pydoc-tools because these package versions have conflicting dependencies.

The conflict is caused by:
    instructor 0.6.4 depends on docstring-parser<0.16 and >=0.15
    pydoc-markdown 4.8.2 depends on docstring-parser<0.12 and >=0.11

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

I tried to remove the version numbers from instructor it still gives dependency issue.

**Comment by abaranovskis-redsamurai** [comment]
hey, probably you refer to Sparrow repo. yes, I seen this conflict, Haystack is using older docstring dependency throuh pydoc-markdown. What I did locally - commented out instructor, installed everything. Removed pydoc-markdown, installed instructor. Pydoc-markdown seems like not essential library.

**Comment by nehashinde-canopy** [comment]
The starling model mentioned in config file is not for commercial use. Which other model is available for commercial use?
