### ISSUE TITLE
TypeError:'function' object is not iterable

### ISSUE THREAD

**Issue by naujoks-stefan** [katanaml/sparrow-donut#4]
Good Morning Andrej,

I have downloaded the project and set it up successfully so far. I use conda and an env with python 3.10.4 per project and installed the requirements with pip. Operating system: Windows 11. If I start sparrow-ui with the command "streamlit run main.py", then the browser "Edge" opens, the ui is visible. However, in the content of the application, the following trace appears:

![Exception](https://github.com/katanaml/sparrow-donut/assets/69203524/6eeac05c-d639-4eb5-8468-d35888154219)

Can you help me please?

Best
Stefan

**Comment by naujoks-stefan** [comment]
I found the solution. 
In your configuration, you assume that the sparrow-data api runs on hugging face. I have solved it for myself below: 
1.) Create Hugging Face Account
2.) Create Write Token generated by Hugging Face. 
3.) Start the API: uvicorn endpoints:app --host 127.0.0.1 --port 8000 --reload 
4.) Copy & Paste Token in Prompt. Start is Error-Free 
5.) In Project Sparrow-UI dashboard.py I commented out api_url and set api_url = api_url = "http://127.0.0.1:8000/api-dataset/v1/sparrow-data/dataset_info"
6.) start sparrow-ui with streamlit run main.py

Result see Images:
![Result1](https://github.com/katanaml/sparrow-donut/assets/69203524/47ae63d5-72d0-4e11-8c86-a55db37dfeff)
![Result2](https://github.com/katanaml/sparrow-donut/assets/69203524/4405bc42-5248-44b9-a50e-40ecd0c94799)
Hope it helps...

**Comment by abaranovskis-redsamurai** [comment]
I checked it, issue was related with libraries, I specified older versions for streamlit_option_menu, streamlit_nested_layout libs and it works now. This is because app is not tested with the latest versions of these libs. Fix is committed. Thanks for using it :)

It should work with Sparrow Data on Hugging Face too.
