### ISSUE TITLE
Repeated tags withuot prdicted text

### ISSUE THREAD

**Issue by narendra-bhole** [katanaml/sparrow-donut#5]
I have 12 various of elecctricity provider invoices. So each proivder has invoice with different unstructure format. I have such around 50 invoices with me. I want to train donut transfor model with these invoices. One of sample file json data is like.
{
“demand_fixed_charge”: “24000.00”,
“wheeling_charges”: “22365.20”,
“reg_asset_charge”: “0.00”,
“energy_charge”: “65274.00”,
“tod_912_energy_charge”: “884.00”,
“tod_1822_energy_charge”: “2024.00”,
“tod_2206_energy_charge”: “906.00Cr”,
“fuel_adj_charge”: “0.00”,
“penalty_exceed_contract”: “0.00”,
“pf_penalty_incentive”: “2841.03Cr”,
“gov_elec_duty”: “23864.65”,
“mah_gov_tax_on_sale”: “3444.85”,
“current_month_bill”: “138109.67”,
“other_sd_interest”: “0.00”,
“dpc_levied”: “0.00”
}

I created dataset and tarined model however I’m getting result with repeated tag like without detecting text.
<s_demand_fixed_charge><s_demand_fixed_charge><s_demand_fixed_charge><s_demand_fixed_charge><s_demand_fixed_charge>
{‘text_sequence’: ‘’}

Please help me to get this resolved

**Comment by abaranovskis-redsamurai** [comment]
This is too complex/specific question to answer. To solve it, consulting work will be required.
