### ISSUE TITLE
Optimize and improve Donut dataset generation

### ISSUE THREAD

**Issue by albertgilopez** [katanaml/sparrow-donut#6]
When executing run_donut.py, I encountered the following problem:

The script was failing to properly generate and split the datasets. Specifically:
1. The code was not correctly handling the file paths, leading to errors when trying to access or create directories.
2. The dataset splitting logic was not working as intended, resulting in incorrect distribution of data across train, validation, and test sets.
3. There were issues with the metadata generation process, causing inconsistencies in the output.

To address these issues, I've submitted a pull request (#7) with the following proposed changes:

1. Refactored the file path handling to use pathlib consistently throughout the code.
2. Improved the dataset splitting logic to ensure correct distribution of data.
3. Enhanced the metadata generation process for better consistency and error handling.
4. Optimized the overall code structure for improved readability and maintainability.

These changes aim to resolve the current issues with the Donut dataset generation process and improve its overall reliability and efficiency. I welcome any feedback or suggestions for further improvements.

**Comment by abaranovskis-redsamurai** [comment]
Thanks!
